# Generated by Django 4.2.14 on 2026-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='client',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del último pago'),
        ),
        migrations.AddField(
            model_name='client',
            name='parcela',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parcela'),
        ),
        migrations.AddField(
            model_name='client',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de registro'),
        ),
        migrations.AddField(
            model_name='client',
            name='semestre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Semestre'),
        ),
    ]
