# Generated by Django 4.2.14 on 2026-06-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Lote')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_clients', models.IntegerField(default=0, verbose_name='Total de Clientes')),
                ('processed_clients', models.IntegerField(default=0, verbose_name='Clientes Procesados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Lote de Llamadas',
                'verbose_name_plural': 'Lotes de Llamadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20, verbose_name='Estado')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcripción')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='calls/%Y/%m/%d/', verbose_name='Archivo de Audio')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='calls.callbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='clients.client')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
