# Generated by Django 4.2.14 on 2026-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='elevenlabs_conversation_id',
            field=models.CharField(blank=True, help_text='ID de conversación en ElevenLabs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='outcome',
            field=models.CharField(blank=True, help_text='Resultado según ElevenLabs (ej: payment_arranged, no_answer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Cantidad de reintentos realizados'),
        ),
        migrations.AddField(
            model_name='callbatch',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea Celery que procesó este lote', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='callbatch',
            name='elevenlabs_batch_id',
            field=models.CharField(blank=True, help_text='ID del lote en ElevenLabs', max_length=200, null=True),
        ),
    ]
