# Generated by Django 4.2.14 on 2026-07-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_elevenlabs_conversation_id_call_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Duración de la llamada en segundos', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='transcript_text',
            field=models.TextField(blank=True, help_text='Transcripción completa de la llamada', null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Archivo de audio MP3 de la llamada', null=True, upload_to='calls/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
