# Generated by Django 4.2.14 on 2026-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_duration_seconds_call_transcript_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='channel',
            field=models.CharField(choices=[('call', 'Llamada telefónica'), ('whatsapp', 'WhatsApp')], default='call', help_text='Canal de esta interacción: llamada o WhatsApp', max_length=20, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='call',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, help_text="ID del mensaje de WhatsApp devuelto por ElevenLabs (solo channel='whatsapp')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='callbatch',
            name='channel',
            field=models.CharField(choices=[('call', 'Llamada telefónica'), ('whatsapp', 'WhatsApp')], default='call', help_text='Canal de contacto usado para este lote: llamada o WhatsApp', max_length=20, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='callbatch',
            name='whatsapp_template_language',
            field=models.CharField(blank=True, default='es', help_text='Código de idioma del template (ej: es, es_AR)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='callbatch',
            name='whatsapp_template_name',
            field=models.CharField(blank=True, help_text="Nombre del template de WhatsApp aprobado en Meta (solo si channel='whatsapp')", max_length=200, null=True),
        ),
    ]
