# Generated by Django 4.2.14 on 2026-09-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_channel_call_whatsapp_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se mandó automáticamente el enlace de pago por WhatsApp al cerrar esta llamada', null=True),
        ),
    ]
