# Generated by Django 4.2.14 on 2026-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_payment_link_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='summary_title',
            field=models.CharField(blank=True, help_text='Título resumen de la conversación generado por ElevenLabs (call_summary_title)', max_length=255, null=True),
        ),
    ]
